openib: add missing include
Add include to fix compilation with GCC >= 14:
dapl/openib_scm/cm.c: In function 'dapli_socket_connected':
dapl/openib_scm/cm.c:576:23: error: implicit declaration of function 'writev'; did you mean 'write'? [-Wimplicit-function-declaration]
  576 |                 len = writev(cm_ptr->socket, iov, 2);

Signed-off-by: Nicolas Morey <nmorey@suse.com>